import { Router } from 'express';
import { authRouter } from './auth.routes';
import { meRouter } from './me.routes';
import { sociosRouter } from './socios.routes';
import { convidadosRouter } from './convidados.routes';
import { mensalidadesRouter } from './mensalidades.routes';
import { pagamentosConvidadosRouter } from './pagamentos-convidados.routes';
import { despesasRouter } from './despesas.routes';
import { categoriasRouter } from './categorias.routes';
import { receitasOutrasRouter } from './receitas-outras.routes';
import { dashboardRouter, situacaoGeralRouter } from './dashboard.routes';
import { inadimplenciaRouter } from './inadimplencia.routes';
import { prestacoesRouter } from './prestacoes.routes';
import { pixRouter } from './pix.routes';
import { configRouter } from './config.routes';
import { babasRouter } from './babas.routes';
import { eventosRouter } from './eventos.routes';
import { suspensoesRouter } from './suspensoes.routes';
import { rankingsRouter } from './rankings.routes';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/me', meRouter);
apiRouter.use('/socios', sociosRouter);
apiRouter.use('/convidados', convidadosRouter);
apiRouter.use('/mensalidades', mensalidadesRouter);
apiRouter.use('/pagamentos-convidados', pagamentosConvidadosRouter);
apiRouter.use('/despesas', despesasRouter);
apiRouter.use('/categorias', categoriasRouter);
apiRouter.use('/receitas-outras', receitasOutrasRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/situacao-geral', situacaoGeralRouter);
apiRouter.use('/inadimplencia', inadimplenciaRouter);
apiRouter.use('/prestacoes', prestacoesRouter);
apiRouter.use('/pix', pixRouter);
apiRouter.use('/config', configRouter);
apiRouter.use('/babas', babasRouter);
apiRouter.use('/eventos', eventosRouter);
apiRouter.use('/suspensoes', suspensoesRouter);
apiRouter.use('/rankings', rankingsRouter);
